### ISSUE TITLE
Travis failing

### ISSUE THREAD

**Issue by babbush** [quantumlib/OpenFermion#337] opened 2018-05-17 16:16 UTC
It looks like Travis is failing on the two open pull requests for reasons that are totally unrelated to those pull requests. I think that perhaps something in the scipy linear programming module has changed? I'm assigning this issue to those with failing open pull requests but @jarrodmcc and I are also going to try to get to the bottom of this!

**Comment by kevinsung** [comment] 2018-05-17 17:29
The problem is that just importing `scipy` does not let you access `scipy.optimize`. I fixed this in my PR. I have no idea why the tests passed up til now though. Seems like some weird import behavior in scipy that was fixed in the latest version.

**Comment by sheilaliuxl** [comment] 2018-05-17 18:29
Also "dim = 6 * 5 / 2" is a float, not able to be used for shape = (dim, dim).
With Kevin's change and this one, it's able to pass all tests now.

**Closed** 2018-05-17 18:30 UTC
Labels: bug, help wanted
