### ISSUE TITLE
Import issue in Colab: comb deprecated

### ISSUE THREAD

**Issue by jacobmarks** [quantumlib/OpenFermion#536] opened 2019-09-05 18:28 UTC
when importing openfermioncirq in colab,
`from scipy.misc import comb, factorial` causes problem "cannot import name comb"

**Comment by vtomole** [comment] 2019-09-05 19:08
It's been moved to `special`

`from scipy.special import comb` works for me.

**Comment by vtomole** [comment] 2019-09-05 19:55
You are using older version of OpenFermion (0.9.0). Please reinstall OpenFermion on Colab and see that it's version is `0.10.0` and try the import again.

**Comment by obriente** [comment] 2020-03-27 15:53
Seems that some people are having issues with this when using pip to install openfermion; does this need to be updated to 0.10.0?

**Comment by kevinsung** [comment] 2020-03-27 22:36
Yes, we need to cut a new release of OpenFermion.

**Comment by mstechly** [comment] 2020-04-14 15:43
I still have this issue with `openfermion==0.11.0`.

**Comment by kevinsung** [comment] 2020-04-14 23:51
@mstechly What command is giving you an issue? How can we reproduce it?

**Comment by warrenalphonso** [comment] 2020-04-15 22:52
I was getting the same issue with pip install. `pip list` showed OpenFermion at 0.9.0. Using developer install was the only way I could get it to update, which fixed the issue. 

Is the pip version not updated? Perhaps it would be better to clarify on the readme if this is the case.

**Comment by kevinsung** [comment] 2020-04-15 23:44
@warrenalphonso `pip install openfermion` installs 0.11.0, [which is the latest version](https://pypi.org/project/openfermion/), for me. Can you try doing that in a fresh virtual environment?

**Comment by warrenalphonso** [comment] 2020-04-16 01:08
Oops you're right, my mistake.

**Comment by mstechly** [comment] 2020-04-22 12:24
@kevinsung couldn't reproduce it, sorry...
It pops in my code from time to time, I'll keep my eye on it and will let you know when it appears again – this time with reproducible example.

**Comment by mstechly** [comment] 2020-05-12 15:21
@kevinsung FYI: it seemed actually the version of the library was overwritten to be `0.10.0` instead of `0.11.0`.
I think this issue can be closed.

**Comment by kevinsung** [comment] 2020-05-12 23:15
This issue is fixed in the latest pip version of OpenFermion and OpenFermion-Cirq.

**Closed by kevinsung** 2020-05-12 23:15 UTC
